#ifndef CM_ERR_CODES_H
#define CM_ERR_CODES_H

typedef enum CmStatusCode {

  // Common errors
  CM_SUCCESS = 0,
  CM_FAIL,
  CM_ERR_NULL_POINTER,
  CM_ERR_ALLOC_FAILED,

  // Matrix errors
  CM_MATRIX_ERR_WRONG_POS,
  CM_MATRIX_ERR_SIZE_MISMATCH,
  CM_MATRIX_ERR_MULT_SIZE_MISMATCH,
  CM_MATRIX_ERR_NOT_SQUARE,
  CM_MATRIX_ERR_INVALID_SIZE,
  CM_MATRIX_ERR_INVALID_ARGUMENT,
  CM_MATRIX_ERR_ZERO,
  CM_MATRIX_ERR_SINGULAR,

  // Numbers
  CM_ERR_ZERO_DIVISION

} CmStatusCode;

#endif
