#ifndef CM_ERR_CODES_H
#define CM_ERR_CODES_H

typedef enum CmStatusCode {

  CM_SUCCESS = 0,
  CM_FAIL,
  CM_ERR_WRONG_POS,
  CM_ERR_NULL_POINTER,
  CM_ERR_SIZE_MISMATCH,
  CM_ERR_MULT_SIZE_MISMATCH,
  CM_ERR_MATRIX_NOT_SQUARE,
  CM_ERR_ALLOC_FAILED,
  CM_ERR_INVALID_SIZE,
  CM_ERR_INVALID_ARGUMENT,
  CM_ERR_ZERO_MATRIX

} CmStatusCode;

#endif
